config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  root to: 'performers#index'

  get 'performers/identification'
  get 'performers/full_body'
  get 'homes/terms'
  get 'homes/policy'
  get 'homes/transaction'
  get 'homes/service'
  get 'homes/job_offer'
  get 'homes/play_content'
  get 'homes/fee'
  get 'homes/confirm'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tests, only: [:index, :show]
  resources :performers, only: [:index, :new, :show, :edit, :update]
  resources :opinions, only: [:index, :new, :create]
  resources :homes, only: [:index, :new, :create, :show, :update, :destroy]
end

app/models/home.rb
class Home < ApplicationRecord
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  
  def index
    @homes = Home.all
  end
  
  def new
    @homes = Home.new
    if user_signed_in?
     @sender = User.find(current_user.id)
    end
    
    p params[:key]
    if params[:status]
      @receiver = User.find(params[:status])
      $receiver = User.find(params[:status])
    else
      @receiver = User.find(params[:key])
      $receiver = User.find(params[:key])
    end
      
  end
  
  def confirm
    @home = Home.last
    @sender = Performer.find(@home.sender_id)
    @receiver = Performer.find(@home.receiver_id)
  end
  
  
  
  def create
    @sender = User.find(current_user.id)
    @receiver = $receiver

    if Home.create(homes_params)
      @home = Home.last
      
      p @home
      UserMailer.requests(@sender,@receiver,@home).deliver_later
      p "test"
      redirect_to homes_confirm_path #, notice: '女の子へリクエストを送信しました。'
    else
      render :new
    end
  end
  
  def show
   @homes = Home.where(sender_id:current_user.id).or(Home.where(receiver_id:current_user.id))
    if nil != params[:request]
      @sender = User.find(current_user.id)
      @receiver = User.find(params[:request])
      @home = Home.find(params[:home_id])
      
      p "home"+@home.request

      UserMailer.request_content(@sender,@receiver,@home).deliver_later
      redirect_to home_path, notice: '手配中です・・・。'
    end
  end
  
  def update
  end
  
  def destroy
    # Home.last.destroy
    # render :new
    
  end
  
  private
  
  def homes_params
    params.require(:home).permit(:request,:sender_id,:receiver_id,:system_fee,:delivery_time)
  end
end

app/helpers/homes_helper.rb
module HomesHelper
  def today_schedule(performer)
    
    case Date.today.wday
    when 0 then
      schedule(performer.sun_start.strftime('%H:%M'),performer.sun_end.strftime('%H:%M'))
    when 1 then
      p "定休日"
    when 2 then
      schedule(performer.tue_start.strftime('%H:%M'),performer.tue_end.strftime('%H:%M'))
    when 3 then
      schedule(performer.wed_start.strftime('%H:%M'),performer.wed_end.strftime('%H:%M'))
    when 4 then
      schedule(performer.thu_start.strftime('%H:%M'),performer.thu_end.strftime('%H:%M'))
    when 5 then
      schedule(performer.fri_start.strftime('%H:%M'),performer.fri_end.strftime('%H:%M'))
    when 6 then
      schedule(performer.sat_start.strftime('%H:%M'),performer.sat_end.strftime('%H:%M'))

    else
      #いずれの値に一致しない時に実行されるとき
    end
    
  end
  
  def calculation_running_time(sender, receiver)
    if sender.user.address.include?("松戸") && receiver.user.address.include?("松戸") or
      sender.user.address.include?("市川") && receiver.user.address.include?("市川") or 
      sender.user.address.include?("葛飾") && receiver.user.address.include?("葛飾") or 
      sender.user.address.include?("葛飾") && receiver.user.address.include?("松戸") or 
      sender.user.address.include?("市川") && receiver.user.address.include?("松戸") then
      
      return 30
      
    elsif sender.user.address.include?("松戸") && receiver.user.address.include?("市川") or 
      sender.user.address.include?("松戸") && receiver.user.address.include?("葛飾") then 

      return 40
      
    elsif sender.user.address.include?("市川") && receiver.user.address.include?("葛飾") or 
      sender.user.address.include?("葛飾") && receiver.user.address.include?("市川") then
      
      return 50
      
    else
      return "計算不可能"
    end
  end
end

app/views/homes/confirm.html.erb
<meta name="robots" content="none">

<% content_for(:html_title) { 'リクエスト内容確認 | 即ボコ女子松戸店' } %>

<h1>リクエスト内容確認</h1>

<div class="container">
  <div class="border border-danger inner">
    <p class="right">
      <% if @sender.user.address.include?("松戸") then %>
        <% fare = 0 %>
      <% else %>
        <% fare = 2000 %>
      <% end %>
      
      <h4>内容確認</h4>
      料金(コース料金<%= @home.system_fee %>円＋指名料2000円＋交通費)：<br>
      <%= @home.system_fee %>円＋2000円＋<%= fare %>円 ＝<%= @home.system_fee + 2000 %>円<br><br>
      
      <% if '計算不可能' != %> 
        <% @home.delivery_time = calculation_running_time(@sender, @receiver) %>
        <% @home.save %>
        <%= "予想到着時間:" + @home.delivery_time.to_s + '分～' + (@home.delivery_time+10).to_s + '分' %><br><br>
      <% else %>
        <%= "予想到着時間:" + "計測範囲外" %><br><br>
      <% end %>
      
      リクエスト内容：<br><%= @receiver.attack %><br>
      <%= "[追加と禁止事項]" if '' != @home.request %><%= @home.request %><br><br>
      届け先住所:<br><%= @sender.user.address %><br><br>
    </p>
    <button type="button" class="m-1 btn btn-light"><%= link_to "戻る", new_home_path(key:  @home.receiver_id) , method: :get %></button>
    <button type="button" class="m-1 btn btn-light"><%= link_to "リクエスト確定", home_path(@sender.user.id, request: @receiver.id, home_id: @home.id) %></button>
  </div>
  
</div>

app/views/homes/fee.html.erb
<% content_for(:html_title) { '利用料金と遊戯範囲の表です。' } %>

<h1>利用料金と遊戯範囲</h1>

<div class="container">
  <div class="row my-5　border border-primary">
    <table class="table">
      <tr><td><%= "利用料金：40分9000円、60分13000円、80分17000円" %></td></tr>
      <tr><td><%= "交通費：松戸市無料、その他2000円" %></td></tr>
      <tr><td><%= "指名料：2000円" %></td></tr>
      <tr><td><%= "その他料金：制服オプション無料、入会費無料" %></td></tr>
      <tr><td><%= "利用エリア：松戸市、市川市、葛飾区" %></td></tr>
      <tr><td><%= "可能施設：自宅〇　ホテル〇" %></td></tr>
    </table>
  </div>
</div>

app/views/homes/index.html.erb
<% content_for(:html_title) { 'リクエスト一覧 | 即ボコ女子松戸店' } %>

<h1>リクエスト内容</h1>

<div class="container">
  
  
  <div class="row my-5 border border-primary">
    
    <% @homes.each do | home | %>
    
      <div class="col"><%= home.created_at.to_s + ":" %></div>
      <div class="col"><%= User.find(home.sender_id).nickname %></div>
      <div class="col"><%= '⇒' %></div>
      <div class="col"><%= link_to home.request ,home_path(home.id) %></div>
      <div class="col"><%= '⇒' %></div>
      <div class="col"><%= User.find(home.receiver_id).nickname %></div>
      
    <% end %>
    
  </div>
  
</div>

app/views/homes/job_offer.html.erb
<% content_for(:html_title) { '風俗嬢求人情報 | ソフトSM | S女 | 格闘技経験者歓迎' } %>

<h1>求人情報</h1>

<div class="container">
  <div class="row my-5">
    <div class="border border-danger inner">
      <p class="center">こんな方におすすめです。</p>
    </div>
  </div>
  
  <div class="row my-5 d-flex align-items-center"> <!--コンテンツを縦の軸の中央に寄せる-->
    <div class="col-5"><%= image_tag '/img/harassment.png', class:'square' %></div>
    <div class="col-lg-7">
      <p class="white">
        いじめを受けた経験からトラウマを持っている方。職場でハラスメントを受けてストレスが溜まっている方。
        立場が上の人を叩く事による解消方法があります。（辛い記憶を楽しい経験で上書きする心理療法)
      </p>
    </div>
  </div>  
  
  <div class="row my-5 d-flex align-items-center">
    <div class="col-5"><%= image_tag '/img/rejection.png', class:'square' %></div>
    <div class="col-lg-7">
      <p class="white">
        恋人同士が行う行為を他人にする事に抵抗がある方。当店では、在籍する女子本人が使用する技を全て決められます。
        なので、<strong>叩く</strong>だけの技のみで登録して、恋人同士が行う行為を行わない事も可能です。
      </p>
    </div>
  </div>  
  
  <div class="row my-5 d-flex align-items-center">
    <div class="col-5"><%= image_tag '/img/preference.png', class:'square' %></div>
    <div class="col-lg-7">
      <p class="white">
        好きな事をしてお金を稼ぎたい方。男性を叩いたり、<strong>嬲ったり</strong>、おしっこかけたりする行為が好きな方が、意外と少なくありません。
    　   抵抗があるのは最初だけのケースが多いようです。報酬は日給3万5千円以上を稼ぐ事も可能です。
    　</p>
    </div>
  </div>  
  
  <div class="row my-5 d-flex align-items-center">
    <div class="col-5"><%= image_tag '/img/safety.png', class:'square' %></div>
    <div class="col-lg-7">
      <p class="white">
        <strong>風俗</strong>は怖いと思っている方。当店では、所轄の警察署より許可を取って運営している優良店です。
        所轄の警察署より指導されている為、安全と衛生面には常に気を使っています。
      </p>
    </div>
  </div>  
  
  <div class="row my-5 d-flex align-items-center">
    <div class="col-5"><%= image_tag '/img/pick-up.png', class:'square' %></div>
    <div class="col-lg-7">
      <p class="white">
        面接や出勤で店へ足を運ぶのが億劫な方。当店では、<strong>ネットの書類審査のみ</strong>で<strong>面接不要</strong>です。
        又、自宅待機と自宅への送迎が可能です(※松戸市、市川市、葛飾区在住の方)。
      </p>
    </div>
  </div> 
  
  <div class="row my-5 d-flex align-items-center">
    <div class="col-5"><%= image_tag '/img/more_tip.png', class:'square' %></div>
    <div class="col-lg-7">
      <p class="white">
        <strong>指名</strong>がくる自信がなくて稼げるかどうかと不安な方。書類審査が通れば、報酬ありの体験を兼ねた研修が受けられます。
        又、待機所への出勤や、待機所で新しい技を提案して登録が認められれば、チップが貰えるチップ制度があります。
      </p>
    </div>
  </div> 
  
  <div class="row my-5 justify-content-center"> <!--コンテンツを横の軸の中央に寄せる-->
    <p class="center">
      応募条件：18歳～34歳迄<br>面接不要、ネット上の書類審査のみ。<br><br>
      ご質問がありましたら、ご意見板、又は、電話にて承っております。
    </p>
  </div> 
  
  <div class="row my-5 justify-content-center">
    <button type="button" class="btn btn-light">
      <%= link_to "ユーザー登録へ", new_user_registration_path %>
    </button>
  </div>
</div>

app/views/homes/new.html.erb
<% content_for(:html_title) { 'リクエスト一覧 | 即ボコ女子松戸店' } %>

<h1>リクエスト</h1>

<div class="container">
  
  <%= form_with(model: @homes, local: true) do |f| %>
    <div class="row">
      ■コース選択：
    </div>
    
    <div class="row mb-3"> &emsp;
      <%= f.radio_button :system_fee, "9000" %>
      <%= f.label :system_fee, '40分9000円', value: '9000' %> &emsp;
      
      
      <%= f.radio_button :system_fee, "13000" %>
      <%= f.label :system_fee, '60分13000円 ', value: '13000' %> &emsp;
     
      
      <%= f.radio_button :system_fee, "17000" %>
      <%= f.label :system_fee, '80分17000円 ', value: '17000' %>
    </div>
  

    <div class="row"> 
      ■リクエスト内容
    </div>
    <div class="col-10">
      <%= @receiver.nickname+"さんからの" %><%= @receiver.performer.attack %><br>
    </div>
      
    <div class="row mt-3">
      &emsp;<%= "その他のリクエストや禁止技があれば記入" %>
    </div>
    <div class="row">
      <div class="col-sm-auto">
        <%= f.text_area :request ,{value: '',size:"80x4"} %>
        <%= f.hidden_field :sender_id, :value => @sender.id %>
        <%= f.hidden_field :receiver_id, :value => @receiver.id %>
      </div>
    </div>
    
    <div class="row"> &emsp;
      <%= f.submit "入力確認画面へ" %>
    </div>    
    
    <div class="row">
      <p>※リクエスト内容により、ご要望にお応えできない場合があります<br>
      ※ネット上でリクエストを行うには、会員登録が必要です</p>
    </div>
  <% end %>
</div>

app/views/homes/play_content.html.erb
<% content_for(:html_title) { '当店の遊戯の流れ' } %>

<h1>プレイ内容</h1>

<div class="container">
  <div class="row my-5">
    <div class="border border-danger inner">
      <p class="center">当店は、女の子が男性に格闘技を仕掛けるサービスです。<br>格闘技は安全を考慮した上で行っております。
      女の子への反撃は禁止となります。<br>当店でお遊びいただいた段階で、<%= link_to "サービス利用規約",homes_service_path %>に同意したものとみなします。<br>
      必ず<%= link_to "サービス利用規約",homes_service_path %>にはお目通しください。</p> 
    </div>
  </div>
  
  <div class="row my-5 d-flex align-items-center">
    <div class="col-5"><%= image_tag '/img/prepaid.png', class:'square' %></div>
    <div class="col-lg-7">
      <p class="white">
        料金を玄関先に置いてください。又、プレイの遂行と濃密な時間を過ごす為に、シャワーを事前に浴びる事が必須となります。
      </p>
    </div>
  </div>

  <div class="row my-5 d-flex align-items-center">
    <div class="col-5"><%= image_tag '/img/change_of_clothes.png', class:'square' %></div>
    <div class="col-lg-7">
      <p class="white">
        料金受取確認後に、女の子がコスプレ衣装に着替えます。コスプレは女子高生か婦警の制服になります。
      </p>
    </div>
  </div>  
  
  <div class="row my-5 d-flex align-items-center">
    <div class="col-md-5"><%= image_tag '/img/penis_trampling.png', class:'square' %></div>
    <div class="col-lg-7">
      <p class="white">
        遊戯を開始します。女の子がエッチな格闘技を仕掛けます。仕掛ける技の内容は女の子により異なります。
      </p>
    </div>
  </div>  
  
  <div class="row my-5 d-flex align-items-center">
    <div class="col-md-5"><%= image_tag '/img/end_of_play.png', class:'square' %></div>
    <div class="col-lg-7">
      <p class="white">
        遊戯を終了します。女の子が元の衣装に着替えて退室します。
      </p>
    </div>
  </div>  
    
  <div class="row my-5 justify-content-center">
    <button type="button" class="btn btn-light">
      <%= link_to "在籍女子へ", performers_path %>
    </button>
  </div>
</div>

app/views/homes/policy.html.erb
<% content_for(:html_title) { 'プライバシーポリシー' } %>

<h1>プライバシーポリシー</h1>

<div class="container">
  <p><strong>即ボコ女子松戸店</strong>（以下，「当社」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。</p>
  
  <h4>第1条（個人情報）</h4>
  <p>「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。</p>
  
  <h4>第2条（個人情報の収集方法）</h4>
  <p>当社は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,当社の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。</p>
  
  <h4>第3条（個人情報を収集・利用する目的）</h4>
  <p>当社が個人情報を収集・利用する目的は，以下のとおりです。</p>
  <ol>
  <li>当社サービスの提供・運営のため</li>
  <li>ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）</li>
  <li>ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び当社が提供する他のサービスの案内のメールを送付するため</li>
  <li>メンテナンス，重要なお知らせなど必要に応じたご連絡のため</li>
  <li>利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため</li>
  <li>ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため</li>
  <li>有料サービスにおいて，ユーザーに利用料金を請求するため</li>
  <li>上記の利用目的に付随する目的</li>
  </ol>
  
  <h4>第4条（利用目的の変更）</h4>
  <ol>
  <li>当社は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。</li>
  <li>利用目的の変更を行った場合には，変更後の目的について，当社所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。</li>
  </ol>
  
  <h4>第5条（個人情報の第三者提供）</h4>
  <ol>
  <li>当社は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。
  <ol>
  <li>人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき</li>
  <li>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき</li>
  <li>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</li>
  <li>予め次の事項を告知あるいは公表し，かつ当社が個人情報保護委員会に届出をしたとき
  <ol>
  <li>利用目的に第三者への提供を含むこと</li>
  <li>第三者に提供されるデータの項目</li>
  <li>第三者への提供の手段または方法</li>
  <li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
  <li>本人の求めを受け付ける方法</li>
  </ol></li></ol></li>
  <li>前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。
  <ol>
  <li>当社が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
  <li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
  <li>個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合</li>
  </ol></li>
  </ol>
  
  <h4>第6条（個人情報の開示）</h4>
  <ol>
  <li>当社は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1，000円の手数料を申し受けます。
  <ol>
  <li>本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合</li>
  <li>当社の業務の適正な実施に著しい支障を及ぼすおそれがある場合</li>
  <li>その他法令に違反することとなる場合</li>
  </ol></li>
  <li>前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。</li>
  </ol>
  
  <h4>第7条（個人情報の訂正および削除）</h4>
  <ol>
  <li>ユーザーは，当社の保有する自己の個人情報が誤った情報である場合には，当社が定める手続きにより，当社に対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。</li>
  <li>当社は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。</li>
  <li>当社は，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。</li>
  </ol>
  
  <h4>第8条（個人情報の利用停止等）</h4>
  <ol>
  <li>当社は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。</li>
  <li>前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。</li>
  <li>当社は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。</li>
  <li>前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。</li>
  </ol>
  
  <h4>第9条（プライバシーポリシーの変更）</h4>
  <ol>
  <li>本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。</li>
  <li>当社が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。</li>
  </ol>
  
  <h4>第10条（お問い合わせ窓口）</h4>
  <p>本ポリシーに関するお問い合わせは，下記の窓口までお願いいたします。</p>
  <p>住所：千葉県松戸市秋山651-27<br>
  社名：即ボコ女子松戸店<br>
  Eメールアドレス：operation@sokuboko.sakura.ne.jp</p>
  
  <p>以上</p>
</div>

app/views/homes/service.html.erb
<% content_for(:html_title) { 'サービスの利用規約について' } %>

<h1>サービス利用規約<</h1>

<div class="container">
  <div class="row my-5">
    <div class="border border-danger inner">
      <h4 class="center">サービス利用規約<br></h4>
      <h5>　以下の不適切な環境や状況下での利用を禁止します。</h5>
        <ol>
          <li>お客様が不潔であり、<strong>女の子</strong>の衛生上好ましくない方の利用。</li>
          <li>不潔な部屋で、女の子がサービスを行うのに不適切な場合。（サービスの前に必ずシャワーとうがいを行って下さい）</li>
          <li>プレイされるお部屋にお客様の以外の第三者がいた場合。</li>
          <li>暴力団関係者、又は、それに準ずる方。</li>
          <li>薬物を使用されている方。</li>
          <li>性病・伝染病に感染している方。</li>
          <li>当店を通さずに会おうとした、又、は会った方。</li>
          <li>性病・伝染病に感染している方。</li>
          <li>悪質な予約のキャンセル行為があった方。</li>
          <li>同業関係者の方。</li>
          <li>本番要求またはそれに付帯する行為。(女の子から誘いがあった場合は応じずに当店まで連絡下さい。)</li>
          <li>サービスメニューにない過剰なサービスの要求。</li>
          <li>盗聴盗撮行為。(発見した場合、犯罪行為として所轄警察署に通報させて頂きます。)</li>
          <li>当店を出発してからのキャンセルについては承り出来ませんのでご了承ください。（当日代金を全額回収させて頂くか、後日当店指定の銀行口座にお振り込みお願い致します）。</li>
          <li>当店の女の子に対するスカウト等の引き抜き行為。(損害金が発生します。)</li>
          <li>その他、当店がふさわしくないと判断させて頂いた方。</li>
          <li>上記禁止事項に該当する点があり、即ボコ女子の会員様として相応しくないと判断いたしました場合には即刻サービスを中止し、女の子は退出いたします。
              なお、その際の料金返金には応じられません。さらに、その後の当店利用を一切遠慮頂くと共に、会員登録の自動削除をさせていただきます。
              また、当店が必要と判断した場合には罰金及び損害賠償として金百万円をご請求いたしますと共に、所轄警察署まで同行いただくことになります。</li>
        </ol>
    </div>
  </div>
</div>