config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  root to: 'performers#index'

  get 'performers/identification'
  get 'performers/full_body'
  get 'homes/terms'
  get 'homes/policy'
  get 'homes/transaction'
  get 'homes/service'
  get 'homes/job_offer'
  get 'homes/play_content'
  get 'homes/fee'
  get 'homes/confirm'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tests, only: [:index, :show]
  resources :performers, only: [:index, :new, :show, :edit, :update]
  resources :opinions, only: [:index, :new, :create]
  resources :homes, only: [:index, :new, :create, :show, :update, :destroy]
end

app/models/performer.rb
class Performer < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  mount_uploader :identification, ImageUploader
  mount_uploader :full_body, ImageUploader
  
end

app/controllers/performers_controller.rb
class PerformersController < ApplicationController
  
  def index
    @performers = Performer.all
  end
  def new
    if user_signed_in?
      @user = User.find(current_user.id)
      @performer = Performer.find_by(user_id:@user.id)
    end
  end

  def show
    @user = User.find(params[:id])
    @performer = Performer.find_by(user_id:@user.id)
    if '審査依頼' == params[:status]
      @performer.progress = '審査中'
      @performer.save
      UserMailer.progress_email(@performer).deliver_later
    end
  end
  
  def edit
    if user_signed_in?
      @certification = User.find(current_user.id)
    end
    @user = User.find(params[:id])
    
  end
  
  def identification
    @user = User.find(current_user.id)
    @performer = Performer.find_by(user_id:@user.id)
  end
  
  def full_body
    @user = User.find(current_user.id)
    @performer = Performer.find_by(user_id:@user.id)
  end
  
  def update
    @certification = User.find(current_user.id)
    if ENV['ADMINISTRATOR_MAIL'] == @certification.email
      @performer = Performer.find(params[:id])
    else
      @performer = Performer.find_by(user_id:current_user.id)
    end
    
    p params[:performer][:examination]
    if @performer.update(perfomer_params)
      if "identification" == params[:performer][:examination]
        redirect_to performers_identification_path
      else
        redirect_to request.referer
      end
    else
      render :new
    end
  end
  
  private
  #ストロングパラメーター
  def perfomer_params
    params.require(:performer).permit(:image,:attack,:age,:three_size,:identification,:full_body,:progress,
     :sun_start,:sun_end,:tue_start,:tue_end,:wed_start,:wed_end,:thu_start,:thu_end,:fri_start,:fri_end,:sat_start,:sat_end)
  end
  
  
end

app/helpers/performers_helper.rb
module PerformersHelper
  def make_plan(week,f)
    case week
    when '日曜日' then
      @start = f.time_select :sun_start, include_blank: true, class: 'form-control'
      @end = f.time_select :sun_end ,include_blank: true, class: 'form-control'
    when '火曜日' then
      @start = f.time_select :tue_start, include_blank: true, class: 'form-control'
      @end = f.time_select :tue_end ,include_blank: true, class: 'form-control'
    when '水曜日' then
      @start = f.time_select :wed_start, include_blank: true, class: 'form-control'
      @end = f.time_select :wed_end ,include_blank: true, class: 'form-control'
    when '木曜日' then
      @start = f.time_select :thu_start, include_blank: true, class: 'form-control'
      @end = f.time_select :thu_end ,include_blank: true, class: 'form-control'
    when '金曜日' then
      @start = f.time_select :fri_start, include_blank: true, class: 'form-control'
      @end = f.time_select :fri_end ,include_blank: true, class: 'form-control'
    when '土曜日' then
      @start = f.time_select :sat_start, include_blank: true, class: 'form-control'
      @end = f.time_select :sat_end ,include_blank: true, class: 'form-control'
    end
    
    return @start+'～'+@end
  end
end

app/views/performers/edit.html.erb
<meta name="robots" content="none">

<% content_for(:html_title) { '登録情報変 | 即ボコ女子松戸店' } %>

<h1>登録情報変更</h1>

<div class="container">
  <% if ENV['ADMINISTRATOR_MAIL'] == @certification.email %>
    <div class="row my-5">
      <p>お店用のプロフィール：</p>
      <table class="table">
        <tr><td>
          <%= form_with(model: @user.performer, local: true) do |f| %>
            <%= "年齢：" %><%= f.text_field :age ,{size:"10"}%>
            <%= f.submit "変更" %>
          <% end %>
        </td></tr>
        <tr><td>
          <%= form_with(model: @user.performer, local: true) do |f| %>
            <%= "スリーサイズ(B-W-H)：" %><%= f.text_field :three_size ,{size:"30"} %>
            <%= f.submit "変更" %>
          <% end %>
        </td></tr>
        <tr><td>
          <%= form_with(model: @user.performer, local: true) do |f| %>
            <%= "可能な攻撃技：" %><%= f.text_area :attack ,{value: 'ビンタ、金蹴り、膝蹴り、お尻ぺんぺん、金玉握り、膝金、電気あんま、手錠拘束、拘束シコシコ尋問、チョークスリーパー、腕十字固め、踏みつけ、金玉殴り、ちんぽビンタ、人間マット、太もも締め',size:"60x8"} %>
            <%= f.submit "変更" %>
          <% end %>
        </td></tr>
      </table>
    </div>  
    
    <div class="row my-5">
      <%= "画像：" %>
      <%= form_with(model: @user.performer, local: true) do |f| %>
        <%= f.file_field :image %>
        <%= f.submit "登録" %>
      <% end %>
    </div>
  <% end %>

      
  <% if '女' == @user.sex || ENV['ADMINISTRATOR_MAIL'] == @certification.email %>
    <div class="row my-5">
      <%= display_thumbnail(@user.performer) %>
    </div>
    
    <div class="row my-5">
      <p>週間スケジュール：</p>
      <table>
        <tr><td>
          <%= form_with(model: @user.performer, local: true) do |f| %>
            <p>可能な日時(定休日 月曜日、店営業18:00～00:00、休暇 00:00～00:00 ) %><br></p>
            <p>
            　日曜日<%= make_plan('日曜日',f) %><br>
            　火曜日<%= make_plan('火曜日',f) %><br>
            　水曜日<%= make_plan('水曜日',f) %><br>
            　木曜日<%= make_plan('木曜日',f) %><br>
            　金曜日<%= make_plan('金曜日',f) %><br>
            　土曜日<%= make_plan('土曜日',f) %><br>
            </p>
            <%= f.submit "変更" %>
          <% end %>
        </td></tr>
      </table>
    </div>
    
    <div class="row my-5">
      <%= form_with(model: @user.performer, local: true) do |f| %>
        <%= "URL or SNSリンク先：" %><%= f.text_field :sns ,{size:"30"} %>
        <%= f.submit "変更" %>
      <% end %>
    </div>
  <% end %>
  
  <div class="row my-5">
    <%= "アカウント情報：" %>
    <table class="table">
      <tr><td><%= "ニックネーム：#{@user.nickname}" %></td></tr>
      <tr><td><%= "Eメール：#{@user.email}" %></td></tr>
      <tr><td><%= "パスワード: xxxxxxxxxxx" %></td></tr>
      <tr><td><%= "住所: #{@user.address}" %></td></tr>
      <tr><td><%= "電話番号: #{@user.telephone_number}" %></td></tr>
      <tr><td><%= "在籍 or 退会：在籍" %></td></tr>
      <td>
        <button type="button"><%= link_to "変更", edit_user_registration_path %></button>
      </td>
    </table>
  </div>
</div>

app/views/performers/full_body.html.erb
<% content_for(:html_title) { '全身写真 | 書類審査申請 | 即ボコ女子松戸店' } %>

<h1>全身写真提出</h1>

<div class="container">
  <div class="row my-5">
    <p>  1・２・3⃣</p>
  </div>
  
  <div class="row my-5">
    <p class="large">全身写真(全身が分かる写真)</p>
  </div>
  
  <div class="row my-5">
    <%= form_with(model: @performer, local: true) do |f| %>
      <%= f.file_field :full_body %>
      <%= f.hidden_field :examination, :value => "full_body" %>
      <%= f.submit "登録" %>
    <% end %>
  </div>
  
  <div class="row my-5">
    <% if @performer.full_body? %>
      <%= image_tag @performer.full_body.url, class: 'thumbnail' %>
    <% end %>
  </div>
  
  <div class="row my-5">
    <%= button_to "完了", "/performers/#{@performer.user_id}", {method: :get, params:{status: '審査依頼'}} %>
  </div>
</div>

app/views/performers/identification.html.erb
<% content_for(:html_title) { '本人確認書類提出　| 書類審査申請 | 即ボコ女子松戸店' } %>

<h1>本人確認書類提出</h1>

<div class="container">
  <div class="row my-5">
    <p>   1・2⃣・3</p>
  </div>
  
  <div class="row my-5">
    <p class="large">本人確認書類(免許書、個人ナンバーカード、学生証※写真付きで住所が確認できる書類の画像)：</p>
  </div>
  
  <div class="row my-5">
    <%= form_with(model: @performer, local: true) do |f| %>
      <%= f.file_field :identification %>
      <%= f.submit "登録" %>
    <% end %>
  </div>
  
  <div class="row my-5">
    <% if @performer.identification? %>
      <%= image_tag @performer.identification.url, class: 'Horizontal'  %>
    <% end %>
  </div>
  
  <div class="row my-5">
    <%= button_to "次へ", performers_full_body_path, {method: :get}  %>
  </div>
</div>

app/views/performers/index.html.erb
<% content_for(:html_title) { '在籍中の女子を紹介' } %>

<h1>在籍女子</h1>

<div class="container">
  
  <div class="row my-5"><!-- 縦のマージンが0～5の内の5(要素の基本サイズ*3) -->
    <!-- 例外が起きた場合は何もしない-->
    <% begin %>
    
      <!-- 店から許可を受けた女子達のサムネイル画像を表示 -->
      <% @performers.each do | performer | %>
      
      　<% if '入店' == performer.progress %>
          <div class="col-sm-auto">
            <%= display_thumbnail(performer) %>
            <div class="col-sm-auto text-center">
              <% if performer.user.nickname? %>
                <span class="small">
                  <%= performer.user.nickname + " (#{performer.age.to_s})" %><br>
                  <%= "B-W-H: " + performer.three_size %><br>
                  <%= "本日 " + today_schedule(performer) %>
                </span>
              <% end %>
            </div>
          </div>
        <% end %>
        
      <% end %>
      
    <% rescue => e %>
    <% end %>
  </div>
  
</div>

app/views/performers/new.html.erb
<% content_for(:html_title) { 'プロフィール入力 | 書類審査申請 | 即ボコ女子松戸店' } %>

<h1>プロフィール入力</h1>

<div class="container">
  <div class="row my-5">
    <p>   "1⃣・2・3" </p>
  </div>
  <div class="row my-5">
    <div class="col-md-7 border border-primary">
      <%= form_with(model: @performer, local: true) do |f| %>
        
        <div class="form-group">
          <%= f.label :"年齢" %><%= ' (例:28)※半角 '%>
          <%= f.text_field :age, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :'スリーサイズ ' %><%= "( 例：F90-50-80)" %>
          <%= f.text_field :three_size, autofocus: true, class: 'form-control' %>
        </div>
        
        <%= f.hidden_field :examination, :value => "identification" %>
        
        <div>
          <%= f.submit "次へ" %>
        </div><br>
      <% end %>
    </div>
  </div>
</div>

app/views/performers/show.html.erb
<meta name="robots" content="none">

<% content_for(:html_title) { 'プロフィール | 即ボコ女子松戸店' } %>

<h1>プロフィール</h1>

<p class="large"><%=   flash[:request]  %></p>

<div class="container">
  <% if nil == @user.performer.progress && '女' == @user.sex %>
    <div class="row my-5">
      <p class="large">面接不要の書類審査を通過後に表示されます</p>
    </div>
    
    <div class="row my-5">
      <button type="button" class="m-1 btn btn-light"><%= link_to "書類審査申請", new_performer_path, class: "large" %></button>
    </div>
  <% elsif '審査中' == @user.performer.progress && '女' == @user.sex %>
    <div class="row my-5">
      <p class="large"><%= @user.nickname %>さんの書類を審査中です。<br>
      審査が完了するまでお待ちください。2～3日経っても判定結果連絡がこない場合はご連絡ください。</p>
    </div>
    
  <% elsif '入店' == @user.performer.progress %>
  <div class="row my-5">
    <div class="col-sm-3">
      <%= display_thumbnail(@user.performer) %>
    </div>
    
    <div class="col-sm-9">
      <p class="large white"><%= @user.nickname+"さんの攻撃技：" %><br><%= @user.performer.attack %></p><br><br>
    
      <!--<button type="button" class="m-1 btn btn-light"><%#= link_to "リクエスト", new_home_path,class: "large", method: "get", params:{status: '製作中'} %></button>-->
      <!--params:{status: params[:id]}で現在のshow/idのidの値を取得して、homes#newへ送る-->
      <%= button_to 'リクエスト', {controller: 'homes', action: 'new'},{method: :get, class: "m-1 btn btn-light large" , params:{status: params[:id]}}%>
    </div>
    
    <table class="table">
      <tr>
        <td>日</td><td>月</td><td>火</td><td>水</td><td>木</td><td>金</td><td>土</td>
      </tr>
      <tr>
        <td><%= schedule(@user.performer.sun_start.strftime('%H:%M'), @user.performer.sun_end.strftime('%H:%M')) %></td>
        <td>定休日</td>
        <td><%= schedule(@user.performer.tue_start.strftime('%H:%M'), @user.performer.tue_end.strftime('%H:%M')) %></td>
        <td><%= schedule(@user.performer.wed_start.strftime('%H:%M'), @user.performer.wed_end.strftime('%H:%M')) %></td>
        <td><%= schedule(@user.performer.thu_start.strftime('%H:%M'), @user.performer.thu_end.strftime('%H:%M')) %></td>
        <td><%= schedule(@user.performer.fri_start.strftime('%H:%M'), @user.performer.fri_end.strftime('%H:%M')) %></td>
        <td><%= schedule(@user.performer.sat_start.strftime('%H:%M'), @user.performer.sat_end.strftime('%H:%M')) %></td>
      </tr>
    </table>
  </div>
  
  <% else %>
  
  <% end %>
  
  <% if  '男' == @user.sex %><!--男の場合-->
    <%= image_tag('/img/mobu.png', class: 'square') %>
    <table class="table">
      <tr><td><%= "ニックネーム：#{@user.nickname}" %></td></tr>
      <tr><td><%= "利用回数：#{@user.trade}" %></td></tr>
      <tr><td><%= "Eメール：#{@user.email}" %></td></tr>
      <tr><td><%= "住所: #{@user.address}" %></td></tr>
      <tr><td><%= "電話番号: #{@user.telephone_number}" %></td></tr>
    </table>
  <% end %>
</div>