config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  root to: 'performers#index'

  get 'performers/identification'
  get 'performers/full_body'
  get 'homes/terms'
  get 'homes/policy'
  get 'homes/transaction'
  get 'homes/service'
  get 'homes/job_offer'
  get 'homes/play_content'
  get 'homes/fee'
  get 'homes/confirm'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tests, only: [:index, :show]
  resources :performers, only: [:index, :new, :show, :edit, :update]
  resources :opinions, only: [:index, :new, :create]
  resources :homes, only: [:index, :new, :create, :show, :update, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <!--スマホ対応-->
    <meta name="viewport" charset="UTF-8" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:html_title) ? yield(:html_title) : "" %> ｜松戸発のM男向けデリヘル風俗!</title>
    
    <!--integrity:html検証,crossorigin:ユーザー認証情報anonymous(不要)-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      
    <!--googleフォント設定-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol:wght@500&family=Kosugi+Maru&family=Potta+One&family=Yomogi&display=swap" rel="stylesheet">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="松戸発のM男向けデリヘル風俗店！女の子からあらゆるエッチな格闘技をその身に受けて昇天させられます。最安値12000円です。ぜひ、お楽しみください。">
    <meta name="keywords" content="デリヘル,デリバリーヘルス,風俗,松戸">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  </head>

  <header>
    <div class="container-fluid">
      
      <!--トップ表示-->
      <div class="row">
        <div class="col-md-9">
          <%= link_to image_tag('symbol.png',class: 'headericon'), performers_path %>
          <span class="x-large"><strong>即ボコ女子</strong></span>
          <span class="small">～<strong>松戸</strong>発。逆転無しの<strong>M男向けデリヘル</strong>。</span>
        </div>
        
        <div class="col-md-3 d-flex align-items-end">
          <span class="medium">営業時間 昼14:00～ 翌2:00<br>連絡先: <address> <a href="tel:070-3304-9100">070-3304-9100</a></address></span>
        </div>
      </div>
      
      <div class="row">
        <div class="col-11">
          <div class="float-right">
            <span class="x-small">女子求人! 面接不要! 5分でネット登録!</span>
          </div>
        </div>
      </div>
      
      <!--ボタン表示-->
      <div class="row">
        <div class="col-6">
          <button type="button" class="m-1 btn btn-light"><%= link_to "プレイ内容", homes_play_content_path %></button>
          <button type="button" class="m-1 btn btn-light"><%= link_to "システム料金", homes_fee_path %></button>
          <button type="button" class="m-1 btn btn-light"><%= link_to "在籍女子", performers_path %></button>
          <button type="button" class="m-1 btn btn-light"><%= link_to "求人情報", homes_job_offer_path %></button>
          
        </div>
        
        <div class="col-6">
          <div class="float-right">
            <% if user_signed_in? %>
              <button type="button" class="m-1 btn btn-light"><%= link_to "ユーザー情報", "/performers/#{@user.id}" %></button>
              <button type="button" class="m-1 btn btn-light"><%= link_to "変更", "/performers/#{@user.id}/edit" %></button>  
              <button type="button" class="m-1 btn btn-light"><%= link_to "ログアウト", destroy_user_session_path, method: "delete" %></button>
            <% else %>
              <button type="button" class="m-1 btn btn-light"><%= link_to "新規登録", new_user_registration_path, method: "get" %></button>
              <button type="button" class="m-1 btn btn-light"><%= link_to "ログイン\n", new_user_session_path, method: "get" %></button>
            <% end %>
          </div>
        </div>
        
      </div>
      
    </div>
  </header>
  
  <body>
    <!--アクセス解析-->
    <% if (Rails.env.production?) && (controller.controller_name != "registrations") %>
      <script src="//accaii.com/rino/script.js" async></script>
      <noscript><img src="//accaii.com/rino/script?guid=on"></noscript>
    <% end %>

    <!--フラッシュ表示-->
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <p><%= notice %></p>
      </div>
    <% end %>
    
    <!--アラート表示-->
    <% if alert.present? %>
      <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <p><%= alert %></p>
      </div>
    <% end %>
    
    <!--コンテンツ内容表示-->
    <%= yield %>
  </body>
  
  <!-- フッダー。管理者権限の場合にフッダーの色を赤色に変更  -->
  <% if nil != @certification && ENV['ADMINISTRATOR_MAIL'] == @certification.email %>
    <a href= "/tests">管理者用のページへ</a>
    <footer class="footer color_red">
  <% else %>
    <footer class="footer color_pink">
  <% end %>
  
    <!-- フッダーリンク -->
    <div class="container-fluid">
      <div class="row mx-5 mt-3">
        <div class="mx-3"><%= link_to '利用規約', homes_terms_path %></div>
        <div class="mx-3"><%= link_to 'プライバシーポリシー', homes_policy_path %></div>
        <div class="mx-3"><%= link_to '特定商取引法に基づく表記', homes_transaction_path %></div>
      </div>
      
      <div class="row mx-5 mt-1">
        <div class="mx-3"><%= link_to 'ご意見・質問フォーム', new_opinion_path %></div>
      </div>
      
      <div class="row mx-5 my-2">
        <div class="col-12">
          <div class="float-right"><p>© 2021-2022 即ボコ女子松戸店</p></div>
        </div>
      </div>
    </div>
    
  </footer>
</html>